# Generated by Django 6.0.4 on 2026-08-19 06:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pms_app', '0003_project'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('t_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('desc', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('todo', 'To Do'), ('in_progress', 'In Progress'), ('review', 'In Review'), ('done', 'Done'), ('cancelled', 'Cancelled')], default='todo', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=50)),
                ('due_date', models.DateTimeField(blank=True, null=True)),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('update_last', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('assign_by', models.ForeignKey(blank=True, db_column='assign_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks_assigned_by_me', to=settings.AUTH_USER_MODEL)),
                ('assign_to', models.ForeignKey(blank=True, db_column='assign_to', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tasks', to='pms_app.teammember')),
                ('created_by', models.ForeignKey(blank=True, db_column='created_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_tasks', to=settings.AUTH_USER_MODEL)),
                ('p', models.ForeignKey(db_column='p_id', on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='pms_app.project')),
            ],
            options={
                'verbose_name': 'Task',
                'db_table': 'tasks',
            },
        ),
    ]
